CurTip = 1

Tips = {
	"As an Agent, killing Civilians that have no weapons will decrease your karma.",
	"As the VIP, killing ANY Civilian will decrease your karma.",
	"Killing Civilians as a Civilian will decrease your karma.",
	"If your karma is too low, you will get BANNED for an amount of minutes specified by the server.",
	"Can't see how to draw your weapon? Look down when you have one.",
	"Need to dispose of a weapon? Look down when you have a weapon equipped.",
	"The chat is distance-based. If you can not see a player's nickname from the range you are at, it means he will not see you write or hear you talk.",
	"Just because a person is marked as 'Suspicious' after examination, it does not mean that the person is an Agent or the VIP.",
	"There is no such thing as 'RDM'. If you're being shot at, it means that the player either suspects or knows that you might be an Agent/VIP.",
	"If you're an Agent, and a certain server console variable is enabled, then you will lose karma if you kill armed Civilians, that did not return fire.",
	"Remain within a group of people. Walking alone may get you killed by an Agent, who suspects you of being an enemy.",
	"Unique weapons such as the Knife, the Dart Gun do not take up a weapon slot, which means that you can carry 2 weapons along with a unique weapon.",
	"Unique weapons still weigh something, so be sure to choose wisely!",
	"Unique weapons are marked with '(U)' in the buy menu",
	"Large weapons such as the MP5, P90 and the UMP .45 are not concealable. As such, they will appear on your back if you conceal them.",
	"Be careful when showing your VIP ID card to other people! The person you show it to might be an Agent!",
	"Did you know that you can attach silencers to almost every weapon? To do so, hold your USE KEY and press your SECONDARY ATTACK KEY.",
	"Each player is able to grab onto low ledges and pull himself up. He can do so by holding down his JUMP KEY. Don't forget to hold your CROUCH KEY after you've pulled yourself up!",
	"You slowly regenerate health over time. However you regenerate only 75% of your lost health.",
	"Keep your weapon concealed in public to decrease suspicion and keep the tension at bay.",
	"The chat is limited by a range. To communicate with people over any range, purchase a Walkie-talkie!",
	"As the VIP, supply fellow Civilians with weapons to get bodyguards. However, be careful when giving out weapons, as you might supply an Agent or reveal your true identity to them.",
	"As a Civilian, your main objective is to protect the VIP, not find out who the Agents are.",
	"After purchasing a Walkie-talkie, you'll be able to use the TEAM chat as the RADIO chat, which means that only people on the same channel see what you write.",
	"You can also use quick pre-made voice chat commands by pressing '1' after purchasing a Walkie-talkie.",
	"Agents are only able to kill a number of armed Civilians specified by the server, if you go over the limit, you'll start losing karma for performing badly as an Agent.",
	"Having a high karma increases the amount of money you start out with each round.",
	"Concealing a lot of equipment may mark you as 'Dangerous' upon examination.",
	"Each 'How to' book lasts one round. It does not increase your weight value.",
	"Agents have access to a Dart gun which fires out poisonous darts. To counter the effect of the poison, purchase an antidote. However, you must act quickly!",
	"Examining a player who is wielding a weapon will instantly mark him as 'Dangerous' and display the weapon name.",
	"You can buy medkits in the buy menu on the 'Other' sub-menu.",
	"As the VIP, Agents can pick-pocket your VIP ID card from you, so don't turn your back on people!",
	"If an Agent does pick-pocket your VIP ID card, then be sure to examine his dead body - you will retrieve your VIP ID from him!",
	"Agents can buy a Knife. It is located at the bottom of the 'Weapon' sub-menu in the buy menu.",
	"Do not trust anyone. You may never know that the person you trust is an Agent.",
	"Each player's stamina regenerates over time. Actions like jumping, sprinting and climbing drain your stamina.",
	"The heart-beat sound, vignetting (darkened screen corners) and slight screen corner blur displays your stamina.",
	"Bodies are bound to be found quickly. Hide dead bodies in places you wouldn't expect a player to look in.",
	"Players can also drown. Players will start drowning as soon as their stamina hits 0%. Don't stay underwater for too long!",
	"Do NOT trust people that randomly accuse other people of being Agents. For all you know, they could be making false accusations or just Mingebags.",
	"Players lose 40% stamina based on the damage they received. Stay out of harm's way if you want to sprint!",
	"You can sprint and shoot with a pistol (which sacrifices a lot of accuracy), but you can't do the same with any other firearm.",
	"Showing a forged VIP ID card as an Agent can help you cause confusion, but can also reveal your true identity or mark you as an impostor.",
	"Killing people in public is bound to have consequences. Follow the suspected Agent/VIP into a secluded place to eliminate.",
	"Did you know that taking aim increases your accuracy and decreases weapon recoil?",
	"Did you know that Civilians and the VIP have increased firearm shoot spread and recoil?",
	"Don't forget to examine dead bodies! Examining dead bodies will give you clues as to who killed the person as well as display the dead person's role.",
	"Standing behind people looks suspicious. If you don't want to get shot - don't stand behind them!",
	"As an Agent, be careful when pick-pocketing other players - they might see you do it!",
	"As an Agent, don't forget to buy help from The Agency when there are a lot of people.",
	"The body armor that you buy will only protect your torso and only by a bit. You're not invincible just because you have armor!",
	"Did you know that weapons' damage decreases over distance?"}